// Generate a deterministic DS bundle entry from src/ui.
// Extracts real PascalCase value exports from each .tsx (so renames like
// Input.tsx→TextField are honored), scoped to exactly src/ui. ponytail: regex
// export-scrape — good enough; the converter filters non-components itself.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const UI = 'src/ui';
const EXCLUDE_FILES = new Set(['operations/CardBoundary.tsx']); // error boundary, not a DS part

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (p.endsWith('.tsx') && !p.includes('.test.')) out.push(p);
  }
  return out;
}

// PascalCase value export with at least one lowercase (excludes ALLCAPS consts like GATE_COPY).
const reExport = /^export\s+(?:async\s+)?(?:function|const|class)\s+([A-Z][A-Za-z0-9]*[a-z][A-Za-z0-9]*)/gm;
const files = walk(UI).sort();
const seen = new Map(); // name -> file (first wins)
const lines = [];
const collisions = [];

for (const f of files) {
  const rel = relative(UI, f).replace(/\.tsx$/, '');
  if (EXCLUDE_FILES.has(relative(UI, f))) continue;
  const src = readFileSync(f, 'utf8');
  const names = [...src.matchAll(reExport)].map((m) => m[1]);
  const fresh = [];
  for (const n of [...new Set(names)]) {
    if (seen.has(n)) { collisions.push(`${n} (${rel} vs ${seen.get(n)})`); continue; }
    seen.set(n, rel);
    fresh.push(n);
  }
  if (fresh.length) lines.push(`export { ${fresh.join(', ')} } from '@ui/${rel}';`);
}

const header = `// AUTO-GENERATED by .ds-sync/gen-barrel.mjs — DS bundle entry (everything in src/ui).\n`;
writeFileSync('.ds-sync/ds-entry.tsx', header + lines.join('\n') + '\n');
console.log(`wrote .ds-sync/ds-entry.tsx — ${seen.size} exports from ${lines.length} modules`);
if (collisions.length) console.log(`skipped ${collisions.length} name collisions:\n  ` + collisions.join('\n  '));
